name: Publish to Chocolatey
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        description: Tag of release you want to publish
        type: string
jobs:
  publish:
    runs-on: windows-latest # choco can only be run on windows
    steps:
      - uses: actions/checkout@v5
      - run: pip install -r scripts/requirements.txt
      - run: python scripts/publish_choco.py ${{ inputs.release_tag || github.event.release.tag_name }}
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_APIKEY }}
